<!--
    Copyright © 2024 AO Kaspersky Lab.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->

<xsl:transform xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
               xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
               version="1.0">

	<xsl:import href="Common.xslt"/>

	<xsl:template match="Searches/Search">

		<xsl:variable name="shouldProcess">
			<xsl:call-template name="shouldProcessControl">
				<xsl:with-param name="control" select="name(..)"/>
				<xsl:with-param name="excludedControls" select="$excludedControls"/>
				<xsl:with-param name="excludedControlsDelimiter" select="$excludedControlsDelimiter"/>
			</xsl:call-template>
		</xsl:variable>

		<xsl:if test="$shouldProcess = 'true'">
			<xsl:element name="CustomizationDictionary">

				<xsl:variable name="id" select="@Id"/>
				<xsl:call-template name="assertId">
					<xsl:with-param name="id" select="$id"/>
				</xsl:call-template>

				<!--Id (used as filename when dictionaries will be splitted into separate files)-->
				<xsl:attribute name="Id">
					<xsl:value-of select="$id"/>
				</xsl:attribute>

				<xsl:call-template name="getAutogeneratedComment">
					<xsl:with-param name="source" select="$source"/>
					<xsl:with-param name="comment" select="$comment"/>
				</xsl:call-template>

				<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
									xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">

					<!--BackgroundDisabled-->
					<xsl:call-template name="generateBrush">
						<xsl:with-param name="key">BackgroundDisabled</xsl:with-param>
						<xsl:with-param name="brushNode" select="BackgroundDisabled"/>
					</xsl:call-template>

					<!--BackgroundFocus-->
					<xsl:call-template name="generateBrush">
						<xsl:with-param name="key">BackgroundFocus</xsl:with-param>
						<xsl:with-param name="brushNode" select="BackgroundFocus"/>
					</xsl:call-template>

					<!--BackgroundHover-->
					<xsl:call-template name="generateBrush">
						<xsl:with-param name="key">BackgroundHover</xsl:with-param>
						<xsl:with-param name="brushNode" select="BackgroundHover"/>
					</xsl:call-template>

					<!--BackgroundNormal-->
					<xsl:call-template name="generateBrush">
						<xsl:with-param name="key">BackgroundNormal</xsl:with-param>
						<xsl:with-param name="brushNode" select="BackgroundNormal"/>
					</xsl:call-template>

					<!--BorderColorDisabled-->
					<xsl:call-template name="generateBrush">
						<xsl:with-param name="key">BorderColorDisabled</xsl:with-param>
						<xsl:with-param name="brushNode" select="BorderColorDisabled"/>
					</xsl:call-template>

					<!--BorderColorFocus-->
					<xsl:call-template name="generateBrush">
						<xsl:with-param name="key">BorderColorFocus</xsl:with-param>
						<xsl:with-param name="brushNode" select="BorderColorFocus"/>
					</xsl:call-template>

					<!--BorderColorHover-->
					<xsl:call-template name="generateBrush">
						<xsl:with-param name="key">BorderColorHover</xsl:with-param>
						<xsl:with-param name="brushNode" select="BorderColorHover"/>
					</xsl:call-template>

					<!--BorderColorNormal-->
					<xsl:call-template name="generateBrush">
						<xsl:with-param name="key">BorderColorNormal</xsl:with-param>
						<xsl:with-param name="brushNode" select="BorderColorNormal"/>
					</xsl:call-template>

					<!--CaretBrush-->
					<xsl:call-template name="generateBrush">
						<xsl:with-param name="key">CaretBrush</xsl:with-param>
						<xsl:with-param name="brushNode" select="CaretBrush"/>
					</xsl:call-template>

					<!--PlaceholderForeground-->
					<xsl:call-template name="generateBrush">
						<xsl:with-param name="key">PlaceholderForeground</xsl:with-param>
						<xsl:with-param name="brushNode" select="PlaceholderForeground"/>
					</xsl:call-template>

					<!--PlaceholderForegroundDisabled-->
					<xsl:call-template name="generateBrush">
						<xsl:with-param name="key">PlaceholderForegroundDisabled</xsl:with-param>
						<xsl:with-param name="brushNode" select="PlaceholderForegroundDisabled"/>
					</xsl:call-template>

					<!--SearchIconForeground-->
					<xsl:call-template name="generateBrush">
						<xsl:with-param name="key">SearchIconForeground</xsl:with-param>
						<xsl:with-param name="brushNode" select="SearchIconForeground"/>
					</xsl:call-template>

					<!--SearchIconForegroundDisabled-->
					<xsl:call-template name="generateBrush">
						<xsl:with-param name="key">SearchIconForegroundDisabled</xsl:with-param>
						<xsl:with-param name="brushNode" select="SearchIconForegroundDisabled"/>
					</xsl:call-template>

					<!--TextForeground-->
					<xsl:call-template name="generateBrush">
						<xsl:with-param name="key">TextForeground</xsl:with-param>
						<xsl:with-param name="brushNode" select="TextForeground"/>
					</xsl:call-template>

					<!--TextForegroundDisabled-->
					<xsl:call-template name="generateBrush">
						<xsl:with-param name="key">TextForegroundDisabled</xsl:with-param>
						<xsl:with-param name="brushNode" select="TextForegroundDisabled"/>
					</xsl:call-template>

				</ResourceDictionary>

			</xsl:element>
		</xsl:if>

	</xsl:template>

</xsl:transform>