// Copyright © 2024 AO Kaspersky Lab.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

namespace Kaspirin.UI.Framework.NativeMethods.Api.Wininet.Enums
{
    /// <summary>
    ///     
    /// <seealso href="https://learn.microsoft.com/en-us/windows/win32/wininet/option-flags">Learn more</seealso>.
    /// </summary>
    public enum InternetOptions : uint
    {
        INTERNET_OPTION_CALLBACK = 1,
        INTERNET_OPTION_CONNECT_TIMEOUT = 2,
        INTERNET_OPTION_CONNECT_RETRIES = 3,
        INTERNET_OPTION_CONNECT_BACKOFF = 4,
        INTERNET_OPTION_SEND_TIMEOUT = 5,
        INTERNET_OPTION_CONTROL_SEND_TIMEOUT = INTERNET_OPTION_SEND_TIMEOUT,
        INTERNET_OPTION_RECEIVE_TIMEOUT = 6,
        INTERNET_OPTION_CONTROL_RECEIVE_TIMEOUT = INTERNET_OPTION_RECEIVE_TIMEOUT,
        INTERNET_OPTION_DATA_SEND_TIMEOUT = 7,
        INTERNET_OPTION_DATA_RECEIVE_TIMEOUT = 8,
        INTERNET_OPTION_HANDLE_TYPE = 9,
        INTERNET_OPTION_LISTEN_TIMEOUT = 11,
        INTERNET_OPTION_READ_BUFFER_SIZE = 12,
        INTERNET_OPTION_WRITE_BUFFER_SIZE = 13,
        INTERNET_OPTION_ASYNC_ID = 15,
        INTERNET_OPTION_ASYNC_PRIORITY = 16,
        INTERNET_OPTION_PARENT_HANDLE = 21,
        INTERNET_OPTION_KEEP_CONNECTION = 22,
        INTERNET_OPTION_REQUEST_FLAGS = 23,
        INTERNET_OPTION_EXTENDED_ERROR = 24,
        INTERNET_OPTION_OFFLINE_MODE = 26,
        INTERNET_OPTION_CACHE_STREAM_HANDLE = 27,
        INTERNET_OPTION_USERNAME = 28,
        INTERNET_OPTION_PASSWORD = 29,
        INTERNET_OPTION_ASYNC = 30,
        INTERNET_OPTION_SECURITY_FLAGS = 31,
        INTERNET_OPTION_SECURITY_CERTIFICATE_STRUCT = 32,
        INTERNET_OPTION_DATAFILE_NAME = 33,
        INTERNET_OPTION_URL = 34,
        INTERNET_OPTION_SECURITY_CERTIFICATE = 35,
        INTERNET_OPTION_SECURITY_KEY_BITNESS = 36,
        INTERNET_OPTION_REFRESH = 37,
        INTERNET_OPTION_PROXY = 38,
        INTERNET_OPTION_SETTINGS_CHANGED = 39,
        INTERNET_OPTION_VERSION = 40,
        INTERNET_OPTION_USER_AGENT = 41,
        INTERNET_OPTION_END_BROWSER_SESSION = 42,
        INTERNET_OPTION_PROXY_USERNAME = 43,
        INTERNET_OPTION_PROXY_PASSWORD = 44,
        INTERNET_OPTION_CONTEXT_VALUE = 45,
        INTERNET_OPTION_CONNECT_LIMIT = 46,
        INTERNET_OPTION_SECURITY_SELECT_CLIENT_CERT = 47,
        INTERNET_OPTION_POLICY = 48,
        INTERNET_OPTION_DISCONNECTED_TIMEOUT = 49,
        INTERNET_OPTION_CONNECTED_STATE = 50,
        INTERNET_OPTION_IDLE_STATE = 51,
        INTERNET_OPTION_OFFLINE_SEMANTICS = 52,
        INTERNET_OPTION_SECONDARY_CACHE_KEY = 53,
        INTERNET_OPTION_CALLBACK_FILTER = 54,
        INTERNET_OPTION_CONNECT_TIME = 55,
        INTERNET_OPTION_SEND_THROUGHPUT = 56,
        INTERNET_OPTION_RECEIVE_THROUGHPUT = 57,
        INTERNET_OPTION_REQUEST_PRIORITY = 58,
        INTERNET_OPTION_HTTP_VERSION = 59,
        INTERNET_OPTION_RESET_URLCACHE_SESSION = 60,
        INTERNET_OPTION_ERROR_MASK = 62,
        INTERNET_OPTION_FROM_CACHE_TIMEOUT = 63,
        INTERNET_OPTION_BYPASS_EDITED_ENTRY = 64,
        INTERNET_OPTION_DIAGNOSTIC_SOCKET_INFO = 67,
        INTERNET_OPTION_CODEPAGE = 68,
        INTERNET_OPTION_CACHE_TIMESTAMPS = 69,
        INTERNET_OPTION_DISABLE_AUTODIAL = 70,
        INTERNET_OPTION_MAX_CONNS_PER_SERVER = 73,
        INTERNET_OPTION_MAX_CONNS_PER_1_0_SERVER = 74,
        INTERNET_OPTION_PER_CONNECTION_OPTION = 75,
        INTERNET_OPTION_DIGEST_AUTH_UNLOAD = 76,
        INTERNET_OPTION_IGNORE_OFFLINE = 77,
        INTERNET_OPTION_IDENTITY = 78,
        INTERNET_OPTION_REMOVE_IDENTITY = 79,
        INTERNET_OPTION_ALTER_IDENTITY = 80,
        INTERNET_OPTION_SUPPRESS_BEHAVIOR = 81,
        INTERNET_OPTION_AUTODIAL_MODE = 82,
        INTERNET_OPTION_AUTODIAL_CONNECTION = 83,
        INTERNET_OPTION_CLIENT_CERT_CONTEXT = 84,
        INTERNET_OPTION_AUTH_FLAGS = 85,
        INTERNET_OPTION_COOKIES_3RD_PARTY = 86,
        INTERNET_OPTION_DISABLE_PASSPORT_AUTH = 87,
        INTERNET_OPTION_SEND_UTF8_SERVERNAME_TO_PROXY = 88,
        INTERNET_OPTION_EXEMPT_CONNECTION_LIMIT = 89,
        INTERNET_OPTION_ENABLE_PASSPORT_AUTH = 90,
        INTERNET_OPTION_HIBERNATE_INACTIVE_WORKER_THREADS = 91,
        INTERNET_OPTION_ACTIVATE_WORKER_THREADS = 92,
        INTERNET_OPTION_RESTORE_WORKER_THREAD_DEFAULTS = 93,
        INTERNET_OPTION_SOCKET_SEND_BUFFER_LENGTH = 94,
        INTERNET_OPTION_PROXY_SETTINGS_CHANGED = 95,
        INTERNET_OPTION_DATAFILE_EXT = 96,
        INTERNET_FIRST_OPTION = INTERNET_OPTION_CALLBACK,
        INTERNET_LAST_OPTION = INTERNET_OPTION_DATAFILE_EXT
    }
}