// Copyright © 2024 AO Kaspersky Lab.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file was automatically generated by the 'Kaspirin.UI.Framework.UiKit.Translator'.
// Code generated by the 'Kaspirin.UI.Framework.UiKit.Translator' is owned by the owner of the input file used when generating it.
// The following copyright applies to the portions of the 'Kaspirin.UI.Framework.UiKit.Translator' located in this file: Copyright © 2024 AO Kaspersky Lab.

using System.Runtime.CompilerServices;
using System.Threading;

namespace Kaspirin.UI.Framework.UiKit.Media.Illustrations
{
    /// </summary>UIKit illustrations with ExampleOne scope.</summary>
    public enum UIKitIllustration_ExampleOne
    {
        UIKitUnset = 0,
        Image1,
        Image2,
    }

    internal static class UIKitIllustrationMetadataRegistrar
    {
#if NETFRAMEWORK
        public static void RegisterMetadata()
#else
        [ModuleInitializer]
        internal static void RegisterMetadata()
#endif
        {
            if (Interlocked.CompareExchange(ref _isRegistered, 1, 0) == 0)
            {
                UIKitIllustrationMetadataStorage.Register(UIKitIllustration_ExampleOne.Image1, isAutoRTL: false, height: 64, width: 64);
                UIKitIllustrationMetadataStorage.Register(UIKitIllustration_ExampleOne.Image2, isAutoRTL: false, height: 64, width: 64);
            }
        }

        private static int _isRegistered = 0;
    }
}