<!--
    Copyright © 2024 AO Kaspersky Lab.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->

<xsl:transform xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
               xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
               version="1.0">

	<xsl:output method="xml" indent="yes" encoding="UTF-8" omit-xml-declaration="yes"/>

	<xsl:param name="commentText"/>

	<xsl:variable name="source" select="UiKit/@Source"/>
	<xsl:variable name="comment" select="$commentText"/>

	<xsl:include href="Common.xslt"/>

	<xsl:template match="UiKit">
		<xsl:element name="Palettes">
			<xsl:apply-templates select="Palettes/Palette" />
		</xsl:element>
	</xsl:template>

	<xsl:template match="Palettes/Palette">
		<xsl:element name="Palette">

			<xsl:variable name="id" select="@Id"/>
			<xsl:call-template name="assertId">
				<xsl:with-param name="id" select="$id"/>
			</xsl:call-template>

			<xsl:attribute name="Id">
				<xsl:value-of select="$id"/>
			</xsl:attribute>

			<xsl:call-template name="getAutogeneratedComment">
				<xsl:with-param name="source" select="$source"/>
				<xsl:with-param name="comment" select="$comment"/>
			</xsl:call-template>

			<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
								xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
				<xsl:for-each select="Brushes/PaletteBrush">
					<xsl:call-template name="generateColor">
						<xsl:with-param name="key" select="@Id"/>
						<xsl:with-param name="value">
							<xsl:call-template name="convertSolidBrushToArgb">
								<xsl:with-param name="solidBrush" select="Brush/SolidBrush" />
							</xsl:call-template>
						</xsl:with-param>
					</xsl:call-template>
				</xsl:for-each>
			</ResourceDictionary>
		</xsl:element>
	</xsl:template>

	<!--Template for removing redundant line breaks-->
	<xsl:template match="*/text()[not(normalize-space())]"/>

</xsl:transform>