// Copyright © 2025 AO Kaspersky Lab.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file was automatically generated by the 'Kaspirin.UI.Framework.UiKit.Translator'.
// Code generated by the 'Kaspirin.UI.Framework.UiKit.Translator' is owned by the owner of the input file used when generating it.
// The following copyright applies to the portions of the 'Kaspirin.UI.Framework.UiKit.Translator' located in this file: Copyright © 2024 AO Kaspersky Lab.


using System.Threading;
using Kaspirin.UI.Framework.UiKit.Palettes;

namespace Kaspirin.UI.Framework.UiKit.Styles.Palette;

public enum UIKitPalette
{
    Transparent = 0,
    BackgroundElevation,
    BackgroundElevationInvert,
    BackgroundIslandElevation,
    BackgroundIslandElevationInvert,
    BackgroundIslandInner,
    BackgroundIslandInnerInvert,
    BackgroundIslandPrimary,
    BackgroundIslandPrimaryInvert,
    BackgroundIslandSecondary,
    BackgroundIslandSecondaryInvert,
    BackgroundOverlay,
    BackgroundPrimary,
    BackgroundPrimaryInvert,
    BackgroundSecondary,
    BackgroundSecondaryInvert,
    ControlsBGBase,
    ControlsBGBaseInvert,
    ControlsBGEmeraldDefaultFocusLoading,
    ControlsBGEmeraldHover,
    ControlsBGEmeraldPressed,
    ControlsBGEmeraldSubtleDefaultFocusLoading,
    ControlsBGEmeraldSubtleHover,
    ControlsBGEmeraldSubtlePressed,
    ControlsBGGrayDefaultFocusLoading,
    ControlsBGGrayHover,
    ControlsBGGrayPressed,
    ControlsBGGraySlimHover,
    ControlsBGGraySlimPressed,
    ControlsBGIslandElevationPressed,
    ControlsBGIslandPrimaryPressed,
    ControlsBGIslandSecondaryPressed,
    ControlsBGRedDefaultFocusLoading,
    ControlsBGRedHover,
    ControlsBGRedPressed,
    ControlsBGWhiteDefaultFocusLoading,
    ControlsBGWhiteHover,
    ControlsBGWhitePressed,
    ElementsLine,
    ElementsLineDanger,
    ElementsLineDangerFocus,
    ElementsLineDangerHover,
    ElementsLineEmerald,
    ElementsLineInvert,
    ElementsSeparator,
    ElementsSeparatorInvert,
    ElementsSeparatorBold,
    ElementsSeparatorBoldHover,
    ElementsSeparatorBoldInvert,
    ElementsSeparatorEmerald,
    ElementsSeparatorEmeraldInvert,
    ElementsSeparatorMarina,
    ElementsSeparatorMarinaInvert,
    ElementsSeparatorRed,
    ElementsSeparatorRedInvert,
    ElementsSeparatorYellow,
    ElementsSeparatorYellowInvert,
    FixedColorAlternative,
    FixedColorAlternative2,
    FixedColorAlternative2White,
    FixedColorAlternative3,
    FixedColorAlternativeWhite,
    FixedColorBase,
    FixedColorBaseIcon,
    FixedColorBaseIconWhite,
    FixedColorBaseWhite,
    FixedColorControlGrayHover,
    FixedColorControlGrayPressed,
    FixedColorDisabled,
    FixedColorDisabledWhite,
    FixedColorLine,
    FixedColorLineWhite,
    FixedColorOverlay,
    FixedColorPrimary,
    FixedColorPrimaryWhite,
    FixedColorSecondary,
    FixedColorSecondary2,
    FixedColorSecondary2White,
    FixedColorSecondaryWhite,
    FixedColorSeparator,
    FixedColorSeparatorBold,
    FixedColorSeparatorBoldWhite,
    FixedColorSeparatorWhite,
    FixedColorSnackbar,
    StatusHigh,
    StatusHighSubtle,
    StatusHighSubtleTransparent20,
    StatusInfo,
    StatusInfoSubtle,
    StatusInfoSubtleTransparent20,
    StatusLow,
    StatusLowSubtle,
    StatusMedium,
    StatusMediumSubtle,
    StatusMediumSubtleTransparent20,
    StatusPositive,
    StatusPositiveSubtle,
    StatusPositiveSubtleTransparent20,
    SurfaceColdGrey,
    SurfaceEmerald,
    SurfaceGrass,
    SurfaceMarengo,
    SurfaceMarina,
    SurfaceOrange,
    SurfacePurple,
    SurfaceRed,
    SurfaceViolet,
    SurfaceYellow,
    TagsEmerald,
    TagsEmeraldInvert,
    TagsGrass,
    TagsGrassInvert,
    TagsMarengo,
    TagsMarengoInvert,
    TagsMarina,
    TagsMarinaInvert,
    TagsNeutral,
    TagsNeutralInvert,
    TagsOrange,
    TagsOrangeInvert,
    TagsPurple,
    TagsPurpleInvert,
    TagsRed,
    TagsRedInvert,
    TagsViolet,
    TagsVioletInvert,
    TagsYellow,
    TagsYellowInvert,
    TextIconsElementsBase,
    TextIconsElementsBaseInvert,
    TextIconsElementsBaseIcon,
    TextIconsElementsBaseIconInvert,
    TextIconsElementsDisabled,
    TextIconsElementsDisabledInvert,
    TextIconsElementsEmerald,
    TextIconsElementsPrimary,
    TextIconsElementsPrimaryInvert,
    TextIconsElementsRed,
    TextIconsElementsSecondary,
    TextIconsElementsSecondaryInvert,
    TextIconsElementsYellow
}

public enum UIKitPaletteScope
{
    UIKitUnset = 0,
    Background,
    ControlsBG,
    Elements,
    FixedColor,
    Status,
    Surface,
    Tags,
    TextIconsElements
}

public sealed class UIKitPaletteExtension : UIKitPaletteExtension<UIKitPalette>
{
    static UIKitPaletteExtension()
    {
        UIKitPaletteMetadataRegistrar.RegisterMetadata();
    }
}

internal static class UIKitPaletteMetadataRegistrar
{
    internal static void RegisterMetadata()
    {
        if (Interlocked.CompareExchange(ref _isRegistered, 1, 0) == 0)
        {
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.BackgroundElevation, scope: UIKitPaletteScope.Background, resourceId: "Background_Elevation");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.BackgroundElevationInvert, scope: UIKitPaletteScope.Background, resourceId: "Background_Elevation-Invert");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.BackgroundIslandElevation, scope: UIKitPaletteScope.Background, resourceId: "Background_Island-Elevation");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.BackgroundIslandElevationInvert, scope: UIKitPaletteScope.Background, resourceId: "Background_Island-Elevation-Invert");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.BackgroundIslandInner, scope: UIKitPaletteScope.Background, resourceId: "Background_Island-Inner");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.BackgroundIslandInnerInvert, scope: UIKitPaletteScope.Background, resourceId: "Background_Island-Inner-Invert");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.BackgroundIslandPrimary, scope: UIKitPaletteScope.Background, resourceId: "Background_Island-Primary");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.BackgroundIslandPrimaryInvert, scope: UIKitPaletteScope.Background, resourceId: "Background_Island-Primary-Invert");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.BackgroundIslandSecondary, scope: UIKitPaletteScope.Background, resourceId: "Background_Island-Secondary");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.BackgroundIslandSecondaryInvert, scope: UIKitPaletteScope.Background, resourceId: "Background_Island-Secondary-Invert");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.BackgroundOverlay, scope: UIKitPaletteScope.Background, resourceId: "Background_Overlay");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.BackgroundPrimary, scope: UIKitPaletteScope.Background, resourceId: "Background_Primary");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.BackgroundPrimaryInvert, scope: UIKitPaletteScope.Background, resourceId: "Background_Primary-Invert");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.BackgroundSecondary, scope: UIKitPaletteScope.Background, resourceId: "Background_Secondary");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.BackgroundSecondaryInvert, scope: UIKitPaletteScope.Background, resourceId: "Background_Secondary-Invert");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ControlsBGBase, scope: UIKitPaletteScope.ControlsBG, resourceId: "ControlsBG_Base");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ControlsBGBaseInvert, scope: UIKitPaletteScope.ControlsBG, resourceId: "ControlsBG_Base-Invert");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ControlsBGEmeraldDefaultFocusLoading, scope: UIKitPaletteScope.ControlsBG, resourceId: "ControlsBG_Emerald-Default-Focus-Loading");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ControlsBGEmeraldHover, scope: UIKitPaletteScope.ControlsBG, resourceId: "ControlsBG_Emerald-Hover");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ControlsBGEmeraldPressed, scope: UIKitPaletteScope.ControlsBG, resourceId: "ControlsBG_Emerald-Pressed");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ControlsBGEmeraldSubtleDefaultFocusLoading, scope: UIKitPaletteScope.ControlsBG, resourceId: "ControlsBG_Emerald-Subtle-Default-Focus-Loading");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ControlsBGEmeraldSubtleHover, scope: UIKitPaletteScope.ControlsBG, resourceId: "ControlsBG_Emerald-Subtle-Hover");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ControlsBGEmeraldSubtlePressed, scope: UIKitPaletteScope.ControlsBG, resourceId: "ControlsBG_Emerald-Subtle-Pressed");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ControlsBGGrayDefaultFocusLoading, scope: UIKitPaletteScope.ControlsBG, resourceId: "ControlsBG_Gray-Default-Focus-Loading");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ControlsBGGrayHover, scope: UIKitPaletteScope.ControlsBG, resourceId: "ControlsBG_Gray-Hover");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ControlsBGGrayPressed, scope: UIKitPaletteScope.ControlsBG, resourceId: "ControlsBG_Gray-Pressed");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ControlsBGGraySlimHover, scope: UIKitPaletteScope.ControlsBG, resourceId: "ControlsBG_Gray-Slim-Hover");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ControlsBGGraySlimPressed, scope: UIKitPaletteScope.ControlsBG, resourceId: "ControlsBG_Gray-Slim-Pressed");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ControlsBGIslandElevationPressed, scope: UIKitPaletteScope.ControlsBG, resourceId: "ControlsBG_Island-Elevation-Pressed");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ControlsBGIslandPrimaryPressed, scope: UIKitPaletteScope.ControlsBG, resourceId: "ControlsBG_Island-Primary-Pressed");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ControlsBGIslandSecondaryPressed, scope: UIKitPaletteScope.ControlsBG, resourceId: "ControlsBG_Island-Secondary-Pressed");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ControlsBGRedDefaultFocusLoading, scope: UIKitPaletteScope.ControlsBG, resourceId: "ControlsBG_Red-Default-Focus-Loading");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ControlsBGRedHover, scope: UIKitPaletteScope.ControlsBG, resourceId: "ControlsBG_Red-Hover");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ControlsBGRedPressed, scope: UIKitPaletteScope.ControlsBG, resourceId: "ControlsBG_Red-Pressed");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ControlsBGWhiteDefaultFocusLoading, scope: UIKitPaletteScope.ControlsBG, resourceId: "ControlsBG_White-Default-Focus-Loading");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ControlsBGWhiteHover, scope: UIKitPaletteScope.ControlsBG, resourceId: "ControlsBG_White-Hover");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ControlsBGWhitePressed, scope: UIKitPaletteScope.ControlsBG, resourceId: "ControlsBG_White-Pressed");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ElementsLine, scope: UIKitPaletteScope.Elements, resourceId: "Elements_Line");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ElementsLineDanger, scope: UIKitPaletteScope.Elements, resourceId: "Elements_Line-Danger");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ElementsLineDangerFocus, scope: UIKitPaletteScope.Elements, resourceId: "Elements_Line-Danger-Focus");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ElementsLineDangerHover, scope: UIKitPaletteScope.Elements, resourceId: "Elements_Line-Danger-Hover");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ElementsLineEmerald, scope: UIKitPaletteScope.Elements, resourceId: "Elements_Line-Emerald");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ElementsLineInvert, scope: UIKitPaletteScope.Elements, resourceId: "Elements_Line-Invert");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ElementsSeparator, scope: UIKitPaletteScope.Elements, resourceId: "Elements_Separator");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ElementsSeparatorInvert, scope: UIKitPaletteScope.Elements, resourceId: "Elements_Separator-Invert");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ElementsSeparatorBold, scope: UIKitPaletteScope.Elements, resourceId: "Elements_SeparatorBold");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ElementsSeparatorBoldHover, scope: UIKitPaletteScope.Elements, resourceId: "Elements_SeparatorBold-Hover");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ElementsSeparatorBoldInvert, scope: UIKitPaletteScope.Elements, resourceId: "Elements_SeparatorBold-Invert");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ElementsSeparatorEmerald, scope: UIKitPaletteScope.Elements, resourceId: "Elements_SeparatorEmerald");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ElementsSeparatorEmeraldInvert, scope: UIKitPaletteScope.Elements, resourceId: "Elements_SeparatorEmerald-Invert");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ElementsSeparatorMarina, scope: UIKitPaletteScope.Elements, resourceId: "Elements_SeparatorMarina");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ElementsSeparatorMarinaInvert, scope: UIKitPaletteScope.Elements, resourceId: "Elements_SeparatorMarina-Invert");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ElementsSeparatorRed, scope: UIKitPaletteScope.Elements, resourceId: "Elements_SeparatorRed");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ElementsSeparatorRedInvert, scope: UIKitPaletteScope.Elements, resourceId: "Elements_SeparatorRed-Invert");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ElementsSeparatorYellow, scope: UIKitPaletteScope.Elements, resourceId: "Elements_SeparatorYellow");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.ElementsSeparatorYellowInvert, scope: UIKitPaletteScope.Elements, resourceId: "Elements_SeparatorYellow-Invert");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.FixedColorAlternative, scope: UIKitPaletteScope.FixedColor, resourceId: "FixedColor_Alternative");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.FixedColorAlternative2, scope: UIKitPaletteScope.FixedColor, resourceId: "FixedColor_Alternative2");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.FixedColorAlternative2White, scope: UIKitPaletteScope.FixedColor, resourceId: "FixedColor_Alternative2White");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.FixedColorAlternative3, scope: UIKitPaletteScope.FixedColor, resourceId: "FixedColor_Alternative3");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.FixedColorAlternativeWhite, scope: UIKitPaletteScope.FixedColor, resourceId: "FixedColor_AlternativeWhite");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.FixedColorBase, scope: UIKitPaletteScope.FixedColor, resourceId: "FixedColor_Base");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.FixedColorBaseIcon, scope: UIKitPaletteScope.FixedColor, resourceId: "FixedColor_BaseIcon");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.FixedColorBaseIconWhite, scope: UIKitPaletteScope.FixedColor, resourceId: "FixedColor_BaseIconWhite");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.FixedColorBaseWhite, scope: UIKitPaletteScope.FixedColor, resourceId: "FixedColor_BaseWhite");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.FixedColorControlGrayHover, scope: UIKitPaletteScope.FixedColor, resourceId: "FixedColor_Control-Gray-Hover");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.FixedColorControlGrayPressed, scope: UIKitPaletteScope.FixedColor, resourceId: "FixedColor_Control-Gray-Pressed");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.FixedColorDisabled, scope: UIKitPaletteScope.FixedColor, resourceId: "FixedColor_Disabled");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.FixedColorDisabledWhite, scope: UIKitPaletteScope.FixedColor, resourceId: "FixedColor_DisabledWhite");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.FixedColorLine, scope: UIKitPaletteScope.FixedColor, resourceId: "FixedColor_Line");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.FixedColorLineWhite, scope: UIKitPaletteScope.FixedColor, resourceId: "FixedColor_LineWhite");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.FixedColorOverlay, scope: UIKitPaletteScope.FixedColor, resourceId: "FixedColor_Overlay");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.FixedColorPrimary, scope: UIKitPaletteScope.FixedColor, resourceId: "FixedColor_Primary");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.FixedColorPrimaryWhite, scope: UIKitPaletteScope.FixedColor, resourceId: "FixedColor_PrimaryWhite");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.FixedColorSecondary, scope: UIKitPaletteScope.FixedColor, resourceId: "FixedColor_Secondary");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.FixedColorSecondary2, scope: UIKitPaletteScope.FixedColor, resourceId: "FixedColor_Secondary2");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.FixedColorSecondary2White, scope: UIKitPaletteScope.FixedColor, resourceId: "FixedColor_Secondary2White");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.FixedColorSecondaryWhite, scope: UIKitPaletteScope.FixedColor, resourceId: "FixedColor_SecondaryWhite");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.FixedColorSeparator, scope: UIKitPaletteScope.FixedColor, resourceId: "FixedColor_Separator");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.FixedColorSeparatorBold, scope: UIKitPaletteScope.FixedColor, resourceId: "FixedColor_SeparatorBold");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.FixedColorSeparatorBoldWhite, scope: UIKitPaletteScope.FixedColor, resourceId: "FixedColor_SeparatorBoldWhite");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.FixedColorSeparatorWhite, scope: UIKitPaletteScope.FixedColor, resourceId: "FixedColor_SeparatorWhite");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.FixedColorSnackbar, scope: UIKitPaletteScope.FixedColor, resourceId: "FixedColor_Snackbar");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.StatusHigh, scope: UIKitPaletteScope.Status, resourceId: "Status_High");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.StatusHighSubtle, scope: UIKitPaletteScope.Status, resourceId: "Status_High-Subtle");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.StatusHighSubtleTransparent20, scope: UIKitPaletteScope.Status, resourceId: "Status_High-Subtle-Transparent_20");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.StatusInfo, scope: UIKitPaletteScope.Status, resourceId: "Status_Info");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.StatusInfoSubtle, scope: UIKitPaletteScope.Status, resourceId: "Status_Info-Subtle");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.StatusInfoSubtleTransparent20, scope: UIKitPaletteScope.Status, resourceId: "Status_Info-Subtle-Transparent_20");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.StatusLow, scope: UIKitPaletteScope.Status, resourceId: "Status_Low");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.StatusLowSubtle, scope: UIKitPaletteScope.Status, resourceId: "Status_Low-Subtle");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.StatusMedium, scope: UIKitPaletteScope.Status, resourceId: "Status_Medium");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.StatusMediumSubtle, scope: UIKitPaletteScope.Status, resourceId: "Status_Medium-Subtle");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.StatusMediumSubtleTransparent20, scope: UIKitPaletteScope.Status, resourceId: "Status_Medium-Subtle-Transparent_20");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.StatusPositive, scope: UIKitPaletteScope.Status, resourceId: "Status_Positive");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.StatusPositiveSubtle, scope: UIKitPaletteScope.Status, resourceId: "Status_Positive-Subtle");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.StatusPositiveSubtleTransparent20, scope: UIKitPaletteScope.Status, resourceId: "Status_Positive-Subtle-Transparent_20");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.SurfaceColdGrey, scope: UIKitPaletteScope.Surface, resourceId: "Surface_ColdGrey");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.SurfaceEmerald, scope: UIKitPaletteScope.Surface, resourceId: "Surface_Emerald");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.SurfaceGrass, scope: UIKitPaletteScope.Surface, resourceId: "Surface_Grass");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.SurfaceMarengo, scope: UIKitPaletteScope.Surface, resourceId: "Surface_Marengo");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.SurfaceMarina, scope: UIKitPaletteScope.Surface, resourceId: "Surface_Marina");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.SurfaceOrange, scope: UIKitPaletteScope.Surface, resourceId: "Surface_Orange");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.SurfacePurple, scope: UIKitPaletteScope.Surface, resourceId: "Surface_Purple");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.SurfaceRed, scope: UIKitPaletteScope.Surface, resourceId: "Surface_Red");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.SurfaceViolet, scope: UIKitPaletteScope.Surface, resourceId: "Surface_Violet");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.SurfaceYellow, scope: UIKitPaletteScope.Surface, resourceId: "Surface_Yellow");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.TagsEmerald, scope: UIKitPaletteScope.Tags, resourceId: "Tags_Emerald");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.TagsEmeraldInvert, scope: UIKitPaletteScope.Tags, resourceId: "Tags_Emerald-Invert");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.TagsGrass, scope: UIKitPaletteScope.Tags, resourceId: "Tags_Grass");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.TagsGrassInvert, scope: UIKitPaletteScope.Tags, resourceId: "Tags_Grass-Invert");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.TagsMarengo, scope: UIKitPaletteScope.Tags, resourceId: "Tags_Marengo");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.TagsMarengoInvert, scope: UIKitPaletteScope.Tags, resourceId: "Tags_Marengo-Invert");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.TagsMarina, scope: UIKitPaletteScope.Tags, resourceId: "Tags_Marina");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.TagsMarinaInvert, scope: UIKitPaletteScope.Tags, resourceId: "Tags_Marina-Invert");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.TagsNeutral, scope: UIKitPaletteScope.Tags, resourceId: "Tags_Neutral");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.TagsNeutralInvert, scope: UIKitPaletteScope.Tags, resourceId: "Tags_Neutral-Invert");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.TagsOrange, scope: UIKitPaletteScope.Tags, resourceId: "Tags_Orange");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.TagsOrangeInvert, scope: UIKitPaletteScope.Tags, resourceId: "Tags_Orange-Invert");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.TagsPurple, scope: UIKitPaletteScope.Tags, resourceId: "Tags_Purple");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.TagsPurpleInvert, scope: UIKitPaletteScope.Tags, resourceId: "Tags_Purple-Invert");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.TagsRed, scope: UIKitPaletteScope.Tags, resourceId: "Tags_Red");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.TagsRedInvert, scope: UIKitPaletteScope.Tags, resourceId: "Tags_Red-Invert");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.TagsViolet, scope: UIKitPaletteScope.Tags, resourceId: "Tags_Violet");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.TagsVioletInvert, scope: UIKitPaletteScope.Tags, resourceId: "Tags_Violet-Invert");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.TagsYellow, scope: UIKitPaletteScope.Tags, resourceId: "Tags_Yellow");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.TagsYellowInvert, scope: UIKitPaletteScope.Tags, resourceId: "Tags_Yellow-Invert");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.TextIconsElementsBase, scope: UIKitPaletteScope.TextIconsElements, resourceId: "Text-Icons-Elements_Base");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.TextIconsElementsBaseInvert, scope: UIKitPaletteScope.TextIconsElements, resourceId: "Text-Icons-Elements_Base-Invert");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.TextIconsElementsBaseIcon, scope: UIKitPaletteScope.TextIconsElements, resourceId: "Text-Icons-Elements_BaseIcon");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.TextIconsElementsBaseIconInvert, scope: UIKitPaletteScope.TextIconsElements, resourceId: "Text-Icons-Elements_BaseIcon-Invert");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.TextIconsElementsDisabled, scope: UIKitPaletteScope.TextIconsElements, resourceId: "Text-Icons-Elements_Disabled");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.TextIconsElementsDisabledInvert, scope: UIKitPaletteScope.TextIconsElements, resourceId: "Text-Icons-Elements_Disabled-Invert");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.TextIconsElementsEmerald, scope: UIKitPaletteScope.TextIconsElements, resourceId: "Text-Icons-Elements_Emerald");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.TextIconsElementsPrimary, scope: UIKitPaletteScope.TextIconsElements, resourceId: "Text-Icons-Elements_Primary");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.TextIconsElementsPrimaryInvert, scope: UIKitPaletteScope.TextIconsElements, resourceId: "Text-Icons-Elements_Primary-Invert");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.TextIconsElementsRed, scope: UIKitPaletteScope.TextIconsElements, resourceId: "Text-Icons-Elements_Red");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.TextIconsElementsSecondary, scope: UIKitPaletteScope.TextIconsElements, resourceId: "Text-Icons-Elements_Secondary");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.TextIconsElementsSecondaryInvert, scope: UIKitPaletteScope.TextIconsElements, resourceId: "Text-Icons-Elements_Secondary-Invert");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.TextIconsElementsYellow, scope: UIKitPaletteScope.TextIconsElements, resourceId: "Text-Icons-Elements_Yellow");
            UIKitPaletteMetadataStorage.Register(color: UIKitPalette.Transparent, scope: UIKitPaletteScope.UIKitUnset, resourceId: "Transparent");
        }
    }

    private static int _isRegistered = 0;
}