// Copyright © 2025 AO Kaspersky Lab.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file was automatically generated by the 'Kaspirin.UI.Framework.UiKit.Translator'.
// Code generated by the 'Kaspirin.UI.Framework.UiKit.Translator' is owned by the owner of the input file used when generating it.
// The following copyright applies to the portions of the 'Kaspirin.UI.Framework.UiKit.Translator' located in this file: Copyright © 2024 AO Kaspersky Lab.

using System;
using Kaspirin.UI.Framework.UiKit.Styles.Palette;
using Kaspirin.UI.Framework.UiKit.Palettes;

namespace Kaspirin.UI.Framework.UiKit.Styles.Fonts;

public enum UIKitFontBrush
{
    Base,
    BaseIcon,
    BaseIconInvert,
    BaseInvert,
    Disabled,
    DisabledInvert,
    Emerald,
    Primary,
    PrimaryInvert,
    Red,
    Secondary,
    SecondaryInvert,
    Yellow
}

public enum UIKitFontStyle
{
    BaseText,
    BaseTextMonospace,
    BaseTextSemibold,
    Button,
    Header1,
    Header2,
    Header3,
    Header3Monospace,
    Header4,
    Header5,
    SmallText,
    SmallTextMedium,
    Subheader
}

public sealed class UIKitFontBrushExtension : UIKitFontBrushExtension<UIKitFontBrush>
{
    static UIKitFontBrushExtension()
    {
        UIKitPaletteMetadataRegistrar.RegisterMetadata();
    }

    protected override string Map(UIKitFontBrush brush) => UIKitFontMetadataProvider.Map(brush);
}

public sealed class UIKitFontPaletteExtension : UIKitFontBrushExtension<UIKitPalette>
{
    static UIKitFontPaletteExtension()
    {
        UIKitPaletteMetadataRegistrar.RegisterMetadata();
    }

    protected override string Map(UIKitPalette brush) => UIKitPaletteMetadataStorage.Get(brush).ResourceKey;
}

public sealed class UIKitFontStyleExtension : UIKitFontStyleExtension<UIKitFontStyle>
{
    protected override string Map(UIKitFontStyle style) => UIKitFontMetadataProvider.Map(style);
}

internal static class UIKitFontMetadataProvider
{
    public static string Map(UIKitFontStyle id)
        => $"UiKitTextStyle{id}";

    public static string Map(UIKitFontBrush id)
    {
        var paletteIdString = $"TextIconsElements{id}";

        var paletteId = (UIKitPalette)Enum.Parse(typeof(UIKitPalette), paletteIdString);

        return UIKitPaletteMetadataStorage.Get(paletteId).ResourceKey;
    }
}